*** 2016-06-09 13:25:56.243 idempiere Log (CLogFile) ***
13:25:56.243 Adempiere.startup: iDempiere(r) Release 3.1_2015-10-31 -Smart Suite ERP, CRM and SCM- (c) 1999-2013 iDempiere(r); Implementation: iDempiere - Supported by iDempiere community [17]
13:25:56.243 Ini.loadProperties: E:\mercurialidempiere/idempiere-test.properties #33 [17]
13:25:57.008 DB.isBuildOK: Build DB=${env.ADEMPIERE_VERSION} 20080428-1232 [17]
13:25:57.008 DB.isBuildOK: Build Cl=3.1.0.qualifier [17]
13:25:57.170-----------> DB.isBuildOK: Build Version Error 

The program assumes build version 3.1.0.qualifier, but database has build version ${env.ADEMPIERE_VERSION} 20080428-1232. 
This is likely to cause hard to fix errors. 
Please contact administrator. [17]
13:25:57.459 Language.getLanguage: Adding Language=en, Country=US, Locale=en_US [17]
13:25:57.459 Language.getLanguage: Adding Language=en, Country=US, Locale=en_US [17]
13:25:57.568 WebEnv.initWeb: Servlet Context Init Parameters: iDempiere Root
ServerRoot=1 [17]
13:25:57.584-----------> EMail.setFrom: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [17]
13:25:57.599-----------> EMail.addTo: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [17]
13:25:57.599-----------> EMail.isValid: From is invalid=null [17]
13:25:57.599-----------> EMail.isValid: From is invalid=null [17]
13:25:57.599-----------> MClient.sendEMail: Could NOT Send Email: Server started: iDempiere (odbz:10.0.5.41) to you @ company.org: Invalid Data (System) [17]
13:25:57.599 WebEnv.initWeb: Servlet Init Parameter: idempiereMonitor [17]
13:25:57.599 AdempiereMonitor.init:  [17]
13:26:00.915-----------> AnnotationConfiguration.configure: ServletContainerInitializers: detected. Class hierarchy: empty [17]
13:26:01.169-----------> ClassLocator.getDependentXMLResources: Replicate resource: ckez
Overwrite bundleresource://179.fwk1480207683:2/metainfo/zk/config.xml
with bundleresource://179.fwk1480207683:19/metainfo/zk/config.xml [17]
13:26:01.169-----------> ClassLocator.getDependentXMLResources: Replicate resource: zk
Overwrite bundleresource://179.fwk1480207683:11/metainfo/zk/config.xml
with bundleresource://179.fwk1480207683:28/metainfo/zk/config.xml [17]
13:26:01.184-----------> ClassLocator.getDependentXMLResources: Replicate resource: zkbind
Overwrite bundleresource://179.fwk1480207683:12/metainfo/zk/config.xml
with bundleresource://179.fwk1480207683:29/metainfo/zk/config.xml [17]
13:26:01.204-----------> ClassLocator.getDependentXMLResources: Replicate resource: zul
Overwrite bundleresource://179.fwk1480207683:14/metainfo/zk/zk.xml
with bundleresource://179.fwk1480207683:31/metainfo/zk/zk.xml [17]
13:26:01.611-----------> LanguageDefinition.<init>: Replicated language: xhtml, overriden by [LanguageDefinition: xhtml] [17]
13:26:01.642-----------> LanguageDefinition.<init>: Replicated language: xul/html, overriden by [LanguageDefinition: xul/html] [17]
13:26:01.704-----------> ClassLocator.getDependentXMLResources: Replicate resource: calendar
Overwrite bundleresource://179.fwk1480207683:1/metainfo/zk/lang-addon.xml
with bundleresource://179.fwk1480207683:18/metainfo/zk/lang-addon.xml [17]
13:26:01.704-----------> ClassLocator.getDependentXMLResources: Replicate resource: ckez
Overwrite bundleresource://179.fwk1480207683:2/metainfo/zk/lang-addon.xml
with bundleresource://179.fwk1480207683:19/metainfo/zk/lang-addon.xml [17]
13:26:01.704-----------> ClassLocator.getDependentXMLResources: Replicate resource: gmapsz
Overwrite bundleresource://179.fwk1480207683:5/metainfo/zk/lang-addon.xml
with bundleresource://179.fwk1480207683:22/metainfo/zk/lang-addon.xml [17]
13:26:01.720-----------> ClassLocator.getDependentXMLResources: Replicate resource: timeline
Overwrite bundleresource://179.fwk1480207683:6/metainfo/zk/lang-addon.xml
with bundleresource://179.fwk1480207683:23/metainfo/zk/lang-addon.xml [17]
13:26:01.720-----------> ClassLocator.getDependentXMLResources: Replicate resource: timeplot
Overwrite bundleresource://179.fwk1480207683:7/metainfo/zk/lang-addon.xml
with bundleresource://179.fwk1480207683:24/metainfo/zk/lang-addon.xml [17]
13:26:01.736-----------> ClassLocator.getDependentXMLResources: Replicate resource: zkbind
Overwrite bundleresource://179.fwk1480207683:12/metainfo/zk/lang-addon.xml
with bundleresource://179.fwk1480207683:29/metainfo/zk/lang-addon.xml [17]
13:26:01.736-----------> ClassLocator.getDependentXMLResources: Replicate resource: zkplus
Overwrite bundleresource://179.fwk1480207683:13/metainfo/zk/lang-addon.xml
with bundleresource://179.fwk1480207683:30/metainfo/zk/lang-addon.xml [17]
13:26:01.961           WebUIServlet.init: iDempiere Web Client started successfully [17]
13:26:03.517-----------> AnnotationConfiguration.configure: ServletContainerInitializers: detected. Class hierarchy: empty [17]

*** 2016-06-09 13:26:03.859 idempiere Log (CLogFile) ***
13:26:06.129-----------> Node: [10.0.5.41]:5701 [adempiere.idempiere/localhost] [3.5.3] No join method is enabled! Starting standalone. [49]
13:26:24.916-----------> DefaultModelFactory.getClass: No class for table with it entity: LCO_WithholdingType [105]
13:35:53.574===========> MCharge.getAccount: NO account for C_Charge_ID=1000003 [137]
13:35:54.459-----------> Fact.isSourceBalanced: NO - Diff=-452.0 - Fact[MPayment[1000099-258741,Receipt=false,PayAmt=452,Discount=0.0,WriteOff=0.0,OverUnder=0.0,AcctSchema[1000000-PAME S.A. UN/35 Cordoba Oro],PostType=A] [137]
13:35:55.963===========> DB.executeUpdate: INSERT INTO C_Payment (AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,IsApproved,Processing,Processed,IsReconciled,C_BankAccount_ID,TaxAmt,R_AvsAddr,R_AvsZip,Posted,C_Payment_ID,TrxType,TenderType,C_Currency_ID,DiscountAmt,C_DocType_ID,PayAmt,C_BPartner_ID,DateTrx,IsAllocated,DocumentNo,IsOnline,DocStatus,DocAction,IsReceipt,WriteOffAmt,OverUnderAmt,IsOverUnderPayment,IsSelfService,IsDelayedCapture,C_Charge_ID,DateAcct,IsPrepayment,C_Payment_UU) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?) [SvrProcess_e370acef-6de8-4969-b3c5-1523b9b49c9c] [137]
org.postgresql.util.PSQLException: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(258741).; State=23505; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:441)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:128)
	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1038)
	at org.compiere.util.DB.executeUpdate(DB.java:1007)
	at org.compiere.model.PO.doInsert(PO.java:2974)
	at org.compiere.model.PO.saveNew(PO.java:2778)
	at org.compiere.model.PO.save(PO.java:2128)
	at org.compiere.model.PO.saveEx(PO.java:2216)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)

13:35:56.238===========> DB.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(258741). [137]
13:35:56.246-----------> MPayment.doInsert: [SvrProcess_e370acef-6de8-4969-b3c5-1523b9b49c9c]Not inserted - C_Payment [137]
13:35:56.626===========> MPayment.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(258741). [137]
13:35:56.693===========> NIBankTransfer.process: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(258741). [137]
org.adempiere.exceptions.AdempiereException: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(258741).
	at org.compiere.model.PO.saveEx(PO.java:2224)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:172)
	at org.compiere.apps.AbstractProcessCtl.startProcess(AbstractProcessCtl.java:466)
	at org.compiere.apps.AbstractProcessCtl.run(AbstractProcessCtl.java:234)
	at org.adempiere.webui.apps.WProcessCtl.process(WProcessCtl.java:197)
	at org.adempiere.webui.apps.AbstractProcessDialog$ProcessDialogRunnable.doRun(AbstractProcessDialog.java:1060)
	at org.adempiere.util.ContextRunnable.run(ContextRunnable.java:38)
	at org.adempiere.webui.apps.DesktopRunnable.run(DesktopRunnable.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

13:38:33.627===========> MCharge.getAccount: NO account for C_Charge_ID=1000003 [58]
13:38:33.977-----------> Fact.isSourceBalanced: NO - Diff=-452.0 - Fact[MPayment[1000101-87922232323,Receipt=false,PayAmt=452,Discount=0.0,WriteOff=0.0,OverUnder=0.0,AcctSchema[1000000-PAME S.A. UN/35 Cordoba Oro],PostType=A] [58]
13:38:34.962===========> DB.executeUpdate: INSERT INTO C_Payment (AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,IsApproved,Processing,Processed,IsReconciled,C_BankAccount_ID,TaxAmt,R_AvsAddr,R_AvsZip,Posted,C_Payment_ID,TrxType,TenderType,C_Currency_ID,DiscountAmt,C_DocType_ID,PayAmt,C_BPartner_ID,DateTrx,IsAllocated,DocumentNo,IsOnline,DocStatus,DocAction,IsReceipt,WriteOffAmt,OverUnderAmt,IsOverUnderPayment,IsSelfService,IsDelayedCapture,C_Charge_ID,DateAcct,IsPrepayment,C_Payment_UU) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?) [SvrProcess_6c198dc4-14cb-4641-87bd-a580155dd0fb] [58]
org.postgresql.util.PSQLException: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323).; State=23505; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:441)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:128)
	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1038)
	at org.compiere.util.DB.executeUpdate(DB.java:1007)
	at org.compiere.model.PO.doInsert(PO.java:2974)
	at org.compiere.model.PO.saveNew(PO.java:2778)
	at org.compiere.model.PO.save(PO.java:2128)
	at org.compiere.model.PO.saveEx(PO.java:2216)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)

13:38:35.125===========> DB.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [58]
13:38:35.128-----------> MPayment.doInsert: [SvrProcess_6c198dc4-14cb-4641-87bd-a580155dd0fb]Not inserted - C_Payment [58]
13:38:35.145===========> MPayment.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [58]
13:38:35.176===========> NIBankTransfer.process: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [58]
org.adempiere.exceptions.AdempiereException: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323).
	at org.compiere.model.PO.saveEx(PO.java:2224)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:172)
	at org.compiere.apps.AbstractProcessCtl.startProcess(AbstractProcessCtl.java:466)
	at org.compiere.apps.AbstractProcessCtl.run(AbstractProcessCtl.java:234)
	at org.adempiere.webui.apps.WProcessCtl.process(WProcessCtl.java:197)
	at org.adempiere.webui.apps.AbstractProcessDialog$ProcessDialogRunnable.doRun(AbstractProcessDialog.java:1060)
	at org.adempiere.util.ContextRunnable.run(ContextRunnable.java:38)
	at org.adempiere.webui.apps.DesktopRunnable.run(DesktopRunnable.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

13:39:11.978===========> MCharge.getAccount: NO account for C_Charge_ID=1000003 [55]
13:39:12.235-----------> Fact.isSourceBalanced: NO - Diff=-452.0 - Fact[MPayment[1000103-87922232323,Receipt=false,PayAmt=452,Discount=0.0,WriteOff=0.0,OverUnder=0.0,AcctSchema[1000000-PAME S.A. UN/35 Cordoba Oro],PostType=A] [55]
13:39:13.722===========> DB.executeUpdate: INSERT INTO C_Payment (AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,IsApproved,Processing,Processed,IsReconciled,C_BankAccount_ID,TaxAmt,R_AvsAddr,R_AvsZip,Posted,C_Payment_ID,TrxType,TenderType,C_Currency_ID,DiscountAmt,C_DocType_ID,PayAmt,C_BPartner_ID,DateTrx,IsAllocated,DocumentNo,IsOnline,DocStatus,DocAction,IsReceipt,WriteOffAmt,OverUnderAmt,IsOverUnderPayment,IsSelfService,IsDelayedCapture,C_Charge_ID,DateAcct,IsPrepayment,C_Payment_UU) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?) [SvrProcess_a0443b38-b581-47cb-b60d-2d09055075a4] [55]
org.postgresql.util.PSQLException: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323).; State=23505; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:441)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:128)
	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1038)
	at org.compiere.util.DB.executeUpdate(DB.java:1007)
	at org.compiere.model.PO.doInsert(PO.java:2974)
	at org.compiere.model.PO.saveNew(PO.java:2778)
	at org.compiere.model.PO.save(PO.java:2128)
	at org.compiere.model.PO.saveEx(PO.java:2216)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)

13:39:14.577===========> DB.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [55]
13:39:14.584-----------> MPayment.doInsert: [SvrProcess_a0443b38-b581-47cb-b60d-2d09055075a4]Not inserted - C_Payment [55]
13:39:14.642===========> MPayment.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [55]
13:39:14.689===========> NIBankTransfer.process: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [55]
org.adempiere.exceptions.AdempiereException: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323).
	at org.compiere.model.PO.saveEx(PO.java:2224)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:172)
	at org.compiere.apps.AbstractProcessCtl.startProcess(AbstractProcessCtl.java:466)
	at org.compiere.apps.AbstractProcessCtl.run(AbstractProcessCtl.java:234)
	at org.adempiere.webui.apps.WProcessCtl.process(WProcessCtl.java:197)
	at org.adempiere.webui.apps.AbstractProcessDialog$ProcessDialogRunnable.doRun(AbstractProcessDialog.java:1060)
	at org.adempiere.util.ContextRunnable.run(ContextRunnable.java:38)
	at org.adempiere.webui.apps.DesktopRunnable.run(DesktopRunnable.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

13:46:34.376===========> MCharge.getAccount: NO account for C_Charge_ID=1000003 [131]
13:46:36.147-----------> Fact.isSourceBalanced: NO - Diff=-452.0 - Fact[MPayment[1000105-87922232323,Receipt=false,PayAmt=452,Discount=0.0,WriteOff=0.0,OverUnder=0.0,AcctSchema[1000000-PAME S.A. UN/35 Cordoba Oro],PostType=A] [131]
13:49:08.148===========> DB.executeUpdate: INSERT INTO C_Payment (AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,IsApproved,Processing,Processed,IsReconciled,C_BankAccount_ID,TaxAmt,R_AvsAddr,R_AvsZip,Posted,C_Payment_ID,TrxType,TenderType,C_Currency_ID,DiscountAmt,C_DocType_ID,PayAmt,C_BPartner_ID,DateTrx,IsAllocated,DocumentNo,IsOnline,DocStatus,DocAction,IsReceipt,WriteOffAmt,OverUnderAmt,IsOverUnderPayment,IsSelfService,IsDelayedCapture,C_Charge_ID,DateAcct,IsPrepayment,C_Payment_UU) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?,?,?,?,?,?,?,?,?,?,?,trunc(cast(? as TIMESTAMP)),?,?) [SvrProcess_cd9a1738-df7b-47ee-9fa2-2c27ae3c3d76] [131]
org.postgresql.util.PSQLException: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323).; State=23505; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:441)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:128)
	at com.sun.proxy.$Proxy3.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1038)
	at org.compiere.util.DB.executeUpdate(DB.java:1007)
	at org.compiere.model.PO.doInsert(PO.java:2974)
	at org.compiere.model.PO.saveNew(PO.java:2778)
	at org.compiere.model.PO.save(PO.java:2128)
	at org.compiere.model.PO.saveEx(PO.java:2216)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)

13:49:09.628===========> DB.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [131]
13:49:09.640-----------> MPayment.doInsert: [SvrProcess_cd9a1738-df7b-47ee-9fa2-2c27ae3c3d76]Not inserted - C_Payment [131]
13:49:10.180===========> MPayment.saveError: SaveErrorNotUnique - ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [131]
13:49:10.263===========> NIBankTransfer.process: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323). [131]
org.adempiere.exceptions.AdempiereException: Could not save record - Require unique data:  

Please change information.: ERROR: llave duplicada viola restricción de unicidad «const_unique_documentno»
  Detail: Ya existe la llave (documentno)=(87922232323).
	at org.compiere.model.PO.saveEx(PO.java:2224)
	at ni.hmil.override.process.NIBankTransfer.generateBankTransfer(NIBankTransfer.java:201)
	at ni.hmil.override.process.NIBankTransfer.doIt(NIBankTransfer.java:141)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:198)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:144)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:172)
	at org.compiere.apps.AbstractProcessCtl.startProcess(AbstractProcessCtl.java:466)
	at org.compiere.apps.AbstractProcessCtl.run(AbstractProcessCtl.java:234)
	at org.adempiere.webui.apps.WProcessCtl.process(WProcessCtl.java:197)
	at org.adempiere.webui.apps.AbstractProcessDialog$ProcessDialogRunnable.doRun(AbstractProcessDialog.java:1060)
	at org.adempiere.util.ContextRunnable.run(ContextRunnable.java:38)
	at org.adempiere.webui.apps.DesktopRunnable.run(DesktopRunnable.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

13:54:30.143===========> NIMPayment.beforeSave: Log desde NINSSMPayment... [105]
13:57:48.817-----------> Prop.loadProperties: E:\mercurialidempiere\home.properties not found [37]
13:57:48.817-----------> Prop.loadProperties: !!WARNING:Please locate yout custom home.properties on iDEMPIERE_HOME. [37]
14:01:56.927-----------> Prop.loadProperties: E:\mercurialidempiere\home.properties not found [38]
14:01:56.927-----------> Prop.loadProperties: !!WARNING:Please locate yout custom home.properties on iDEMPIERE_HOME. [38]
17:12:21.562-----------> ClusterService: [10.0.5.41]:5701 [adempiere.idempiere/localhost] [3.5.3] Resetting master confirmation timestamps because of huge system clock jump! Clock-Jump: 10605652ms, Master-Confirmation-Timeout: 500000ms. [91]
17:12:25.880-----------> BasicResourcePool.log: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@3ed8c607 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (2). Last acquisition attempt exception:  [47]
org.postgresql.util.PSQLException: El intento de conexión falló.; State=08001; ErrorCode=0
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:257)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1127)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1114)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1855)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
caused by: java.net.NoRouteToHostException: No route to host: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:129)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)

17:12:25.880-----------> BasicResourcePool.log: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@490e4ab3 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (2). Last acquisition attempt exception:  [45]
org.postgresql.util.PSQLException: El intento de conexión falló.; State=08001; ErrorCode=0
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:257)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1127)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1114)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1855)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
caused by: java.net.NoRouteToHostException: No route to host: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:129)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)

17:12:25.880-----------> BasicResourcePool.log: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@9b115cd -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (2). Last acquisition attempt exception:  [46]
org.postgresql.util.PSQLException: El intento de conexión falló.; State=08001; ErrorCode=0
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:257)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1127)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1114)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1855)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
caused by: java.net.NoRouteToHostException: No route to host: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:129)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)

17:12:25.880-----------> BasicResourcePool.log: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3c3c458c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. [47]
17:12:25.883-----------> BasicResourcePool.log: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3c3c458c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. [45]
17:12:25.885-----------> BasicResourcePool.log: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3c3c458c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. [46]
17:12:25.885-----------> BasicResourcePool.log: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@2e9eef62 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (2). Last acquisition attempt exception:  [45]
org.postgresql.util.PSQLException: El intento de conexión falló.; State=08001; ErrorCode=0
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:257)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1127)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1114)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1855)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
caused by: java.net.NoRouteToHostException: No route to host: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:129)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)

17:12:25.885-----------> BasicResourcePool.log: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@494a533d -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (2). Last acquisition attempt exception:  [47]
org.postgresql.util.PSQLException: El intento de conexión falló.; State=08001; ErrorCode=0
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:257)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1127)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1114)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1855)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
caused by: java.net.NoRouteToHostException: No route to host: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:129)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:149)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)

17:12:25.885-----------> BasicResourcePool.log: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3c3c458c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. [45]
17:12:25.889-----------> BasicResourcePool.log: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3c3c458c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. [47]
17:23:01.700===========> PreparedStatementProxy.init: SELECT statement_timestamp() [152]
java.lang.IllegalStateException: DB.getConnectionRO - @NoDBConnection@
	at org.compiere.util.DB.createConnection(DB.java:470)
	at org.idempiere.db.util.AutoCommitConnectionBroker.getConnection(AutoCommitConnectionBroker.java:48)
	at org.compiere.db.PreparedStatementProxy.init(PreparedStatementProxy.java:64)
	at org.compiere.db.PreparedStatementProxy.<init>(PreparedStatementProxy.java:45)
	at org.compiere.db.ProxyFactory.newCPreparedStatement(ProxyFactory.java:56)
	at org.compiere.util.DB.prepareStatement(DB.java:773)
	at org.compiere.util.DB.prepareStatement(DB.java:742)
	at org.compiere.util.DB.getSQLValueTSEx(DB.java:1521)
	at org.compiere.util.DB.getSQLValueTS(DB.java:1565)
	at org.compiere.server.AcctProcessor.postSession(AcctProcessor.java:100)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:79)
	at org.compiere.server.AdempiereServer.doRun(AdempiereServer.java:211)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:190)
	at org.compiere.server.AdempiereServerMgr$ServerWrapper.run(AdempiereServerMgr.java:504)

17:23:01.700===========> PreparedStatementProxy.init: SELECT statement_timestamp() [136]
java.lang.IllegalStateException: DB.getConnectionRO - @NoDBConnection@
	at org.compiere.util.DB.createConnection(DB.java:470)
	at org.idempiere.db.util.AutoCommitConnectionBroker.getConnection(AutoCommitConnectionBroker.java:48)
	at org.compiere.db.PreparedStatementProxy.init(PreparedStatementProxy.java:64)
	at org.compiere.db.PreparedStatementProxy.<init>(PreparedStatementProxy.java:45)
	at org.compiere.db.ProxyFactory.newCPreparedStatement(ProxyFactory.java:56)
	at org.compiere.util.DB.prepareStatement(DB.java:773)
	at org.compiere.util.DB.prepareStatement(DB.java:742)
	at org.compiere.util.DB.getSQLValueTSEx(DB.java:1521)
	at org.compiere.util.DB.getSQLValueTS(DB.java:1565)
	at org.compiere.server.AcctProcessor.postSession(AcctProcessor.java:100)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:79)
	at org.compiere.server.AdempiereServer.doRun(AdempiereServer.java:211)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:190)
	at org.compiere.server.AdempiereServerMgr$ServerWrapper.run(AdempiereServerMgr.java:504)

17:23:20.644===========> DB.getSQLValueTS: SELECT CURRENT_TIMESTAMP FROM DUAL [152]
org.adempiere.exceptions.DBException: java.lang.IllegalStateException: DB.getConnectionRO - No Database Connection
	at org.compiere.db.PreparedStatementProxy.init(PreparedStatementProxy.java:73)
	at org.compiere.db.PreparedStatementProxy.<init>(PreparedStatementProxy.java:45)
	at org.compiere.db.ProxyFactory.newCPreparedStatement(ProxyFactory.java:56)
	at org.compiere.util.DB.prepareStatement(DB.java:773)
	at org.compiere.util.DB.prepareStatement(DB.java:742)
	at org.compiere.util.DB.getSQLValueTSEx(DB.java:1521)
	at org.compiere.util.DB.getSQLValueTS(DB.java:1565)
	at org.compiere.server.AcctProcessor.postSession(AcctProcessor.java:100)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:79)
	at org.compiere.server.AdempiereServer.doRun(AdempiereServer.java:211)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:190)
	at org.compiere.server.AdempiereServerMgr$ServerWrapper.run(AdempiereServerMgr.java:504)
caused by: java.lang.IllegalStateException: DB.getConnectionRO - @NoDBConnection@
	at org.compiere.util.DB.createConnection(DB.java:470)
	at org.idempiere.db.util.AutoCommitConnectionBroker.getConnection(AutoCommitConnectionBroker.java:48)
	at org.compiere.db.PreparedStatementProxy.init(PreparedStatementProxy.java:64)
	at org.compiere.db.PreparedStatementProxy.<init>(PreparedStatementProxy.java:45)
	at org.compiere.db.ProxyFactory.newCPreparedStatement(ProxyFactory.java:56)
	at org.compiere.util.DB.prepareStatement(DB.java:773)
	at org.compiere.util.DB.prepareStatement(DB.java:742)
	at org.compiere.util.DB.getSQLValueTSEx(DB.java:1521)
	at org.compiere.util.DB.getSQLValueTS(DB.java:1565)
	at org.compiere.server.AcctProcessor.postSession(AcctProcessor.java:100)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:79)
	at org.compiere.server.AdempiereServer.doRun(AdempiereServer.java:211)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:190)
	at org.compiere.server.AdempiereServerMgr$ServerWrapper.run(AdempiereServerMgr.java:504)

17:23:20.662===========> DB.getSQLValueTS: SELECT CURRENT_TIMESTAMP FROM DUAL [136]
org.adempiere.exceptions.DBException: java.lang.IllegalStateException: DB.getConnectionRO - No Database Connection
	at org.compiere.db.PreparedStatementProxy.init(PreparedStatementProxy.java:73)
	at org.compiere.db.PreparedStatementProxy.<init>(PreparedStatementProxy.java:45)
	at org.compiere.db.ProxyFactory.newCPreparedStatement(ProxyFactory.java:56)
	at org.compiere.util.DB.prepareStatement(DB.java:773)
	at org.compiere.util.DB.prepareStatement(DB.java:742)
	at org.compiere.util.DB.getSQLValueTSEx(DB.java:1521)
	at org.compiere.util.DB.getSQLValueTS(DB.java:1565)
	at org.compiere.server.AcctProcessor.postSession(AcctProcessor.java:100)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:79)
	at org.compiere.server.AdempiereServer.doRun(AdempiereServer.java:211)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:190)
	at org.compiere.server.AdempiereServerMgr$ServerWrapper.run(AdempiereServerMgr.java:504)
caused by: java.lang.IllegalStateException: DB.getConnectionRO - @NoDBConnection@
	at org.compiere.util.DB.createConnection(DB.java:470)
	at org.idempiere.db.util.AutoCommitConnectionBroker.getConnection(AutoCommitConnectionBroker.java:48)
	at org.compiere.db.PreparedStatementProxy.init(PreparedStatementProxy.java:64)
	at org.compiere.db.PreparedStatementProxy.<init>(PreparedStatementProxy.java:45)
	at org.compiere.db.ProxyFactory.newCPreparedStatement(ProxyFactory.java:56)
	at org.compiere.util.DB.prepareStatement(DB.java:773)
	at org.compiere.util.DB.prepareStatement(DB.java:742)
	at org.compiere.util.DB.getSQLValueTSEx(DB.java:1521)
	at org.compiere.util.DB.getSQLValueTS(DB.java:1565)
	at org.compiere.server.AcctProcessor.postSession(AcctProcessor.java:100)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:79)
	at org.compiere.server.AdempiereServer.doRun(AdempiereServer.java:211)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:190)
	at org.compiere.server.AdempiereServerMgr$ServerWrapper.run(AdempiereServerMgr.java:504)

