*** 2016-11-22 09:09:33.608 idempiere Log (CLogFile) ***
09:09:33.608 Adempiere.startup: iDempiere(r) Release 3.1_2015-10-31 -Smart Suite ERP, CRM and SCM- (c) 1999-2013 iDempiere(r); Implementation: iDempiere - Supported by iDempiere community [17]
09:09:33.608 Ini.loadProperties: E:\mercurialidempiere/idempiere-dev.properties #33 [17]
09:09:34.476 PipoDictionaryService.merge: zipFilepath->C:\Users\OBENAV~1\AppData\Local\Temp\ni.idempiere.importcurrencyrate5305138808323603215.zip [17]
09:09:34.581 PipoDictionaryService.merge: dict file->C:\Users\OBENAV~1\AppData\Local\Temp\ni.idempiere.importcurrencyrate\dict\PackOut.xml [17]
09:09:42.802 PipoDictionaryService.merge: commit PipoDS_46ac3dea-3c0e-46e1-9290-f79816dcb355 [17]
09:09:43.134 DB.isBuildOK: Build DB=${env.ADEMPIERE_VERSION} 20080428-1232 [17]
09:09:43.134 DB.isBuildOK: Build Cl=3.1.0.qualifier [17]
09:09:43.165-----------> DB.isBuildOK: Build Version Error 

The program assumes build version 3.1.0.qualifier, but database has build version ${env.ADEMPIERE_VERSION} 20080428-1232. 
This is likely to cause hard to fix errors. 
Please contact administrator. [17]
09:09:43.420 WebEnv.initWeb: Servlet Context Init Parameters: iDempiere Root
ServerRoot=1 [17]
09:09:43.639-----------> EMail.setFrom: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [17]
09:09:43.639-----------> EMail.addTo: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [17]
09:09:43.639-----------> EMail.isValid: From is invalid=null [17]
09:09:43.639-----------> EMail.isValid: From is invalid=null [17]
09:09:43.639-----------> MClient.sendEMail: Could NOT Send Email: Server started: iDempiere (odbz:192.168.47.1) to you @ company.org: Invalid Data (System) [17]
09:09:43.639 WebEnv.initWeb: Servlet Init Parameter: idempiereMonitor [17]
09:09:43.639 AdempiereMonitor.init:  [17]
09:09:45.883-----------> AnnotationConfiguration.configure: ServletContainerInitializers: detected. Class hierarchy: empty [17]
09:09:46.222-----------> ClassLocator.getDependentXMLResources: Replicate resource: ckez
Overwrite bundleresource://188.fwk491298318:2/metainfo/zk/config.xml
with bundleresource://188.fwk491298318:19/metainfo/zk/config.xml [17]
09:09:46.222-----------> ClassLocator.getDependentXMLResources: Replicate resource: zk
Overwrite bundleresource://188.fwk491298318:11/metainfo/zk/config.xml
with bundleresource://188.fwk491298318:28/metainfo/zk/config.xml [17]
09:09:46.222-----------> ClassLocator.getDependentXMLResources: Replicate resource: zkbind
Overwrite bundleresource://188.fwk491298318:12/metainfo/zk/config.xml
with bundleresource://188.fwk491298318:29/metainfo/zk/config.xml [17]
09:09:46.250-----------> ClassLocator.getDependentXMLResources: Replicate resource: zul
Overwrite bundleresource://188.fwk491298318:14/metainfo/zk/zk.xml
with bundleresource://188.fwk491298318:31/metainfo/zk/zk.xml [17]
09:09:46.661-----------> LanguageDefinition.<init>: Replicated language: xhtml, overriden by [LanguageDefinition: xhtml] [17]
09:09:46.677-----------> LanguageDefinition.<init>: Replicated language: xul/html, overriden by [LanguageDefinition: xul/html] [17]
09:09:46.755-----------> ClassLocator.getDependentXMLResources: Replicate resource: calendar
Overwrite bundleresource://188.fwk491298318:1/metainfo/zk/lang-addon.xml
with bundleresource://188.fwk491298318:18/metainfo/zk/lang-addon.xml [17]
09:09:46.755-----------> ClassLocator.getDependentXMLResources: Replicate resource: ckez
Overwrite bundleresource://188.fwk491298318:2/metainfo/zk/lang-addon.xml
with bundleresource://188.fwk491298318:19/metainfo/zk/lang-addon.xml [17]
09:09:46.755-----------> ClassLocator.getDependentXMLResources: Replicate resource: gmapsz
Overwrite bundleresource://188.fwk491298318:5/metainfo/zk/lang-addon.xml
with bundleresource://188.fwk491298318:22/metainfo/zk/lang-addon.xml [17]
09:09:46.771-----------> ClassLocator.getDependentXMLResources: Replicate resource: timeline
Overwrite bundleresource://188.fwk491298318:6/metainfo/zk/lang-addon.xml
with bundleresource://188.fwk491298318:23/metainfo/zk/lang-addon.xml [17]
09:09:46.771-----------> ClassLocator.getDependentXMLResources: Replicate resource: timeplot
Overwrite bundleresource://188.fwk491298318:7/metainfo/zk/lang-addon.xml
with bundleresource://188.fwk491298318:24/metainfo/zk/lang-addon.xml [17]
09:09:46.786-----------> ClassLocator.getDependentXMLResources: Replicate resource: zkbind
Overwrite bundleresource://188.fwk491298318:12/metainfo/zk/lang-addon.xml
with bundleresource://188.fwk491298318:29/metainfo/zk/lang-addon.xml [17]
09:09:46.786-----------> ClassLocator.getDependentXMLResources: Replicate resource: zkplus
Overwrite bundleresource://188.fwk491298318:13/metainfo/zk/lang-addon.xml
with bundleresource://188.fwk491298318:30/metainfo/zk/lang-addon.xml [17]
09:09:47.115           WebUIServlet.init: iDempiere Web Client started successfully [17]
09:09:48.219-----------> AnnotationConfiguration.configure: ServletContainerInitializers: detected. Class hierarchy: empty [17]

*** 2016-11-22 09:09:48.453 idempiere Log (CLogFile) ***
09:09:49.801-----------> Node: [192.168.163.1]:5701 [adempiere.idempiere/localhost] [3.5.3] No join method is enabled! Starting standalone. [48]
09:09:48.582===========> NotificationValidator.initialize: NotificationValidator.initialize() [75]
org.postgresql.util.PSQLException: ERROR: no existe la relación «ni_notification_trigguer»
  Position: 81; State=42P01; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:128)
	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)
	at ni.idempiere.model.NotificationValidator.initialize(NotificationValidator.java:45)
	at org.adempiere.base.event.AbstractEventHandler.bindEventManager(AbstractEventHandler.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:430)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bind(ServiceComponentProp.java:218)

09:09:50.490-----------> PackInHandler.dumpUnresolvedElements: AD_Menu_Trl [Name=Notificaciones, Description=, AD_Language=es_NI, IsActive=Y, IsTranslated=N] [41]
09:09:50.490-----------> PackInHandler.dumpUnresolvedElements: AD_Menu [Parent_ID=158, SeqNo=3, AD_Client_ID=0, AD_Org_ID=0, Name=Notifications, Description=, Action=W, AD_Window_ID=8f315c93-59f3-48b3-8196-2cfcef9b0b06, AD_Workflow_ID=, AD_Task_ID=, IsActive=Y, IsSummary=N, AD_Process_ID=, IsSOTrx=N, AD_Form_ID=, IsReadOnly=N, EntityType=U, IsCentrallyMaintained=Y, AD_Menu_UU=5019f6b3-f851-4a0c-b634-3ec4d69264d1, AD_InfoWindow_ID=] unresolved [AD_Window_ID] [41]
09:09:50.490===========> PackIn.importXML: importXML: [41]
org.adempiere.exceptions.AdempiereException: Unresolved elements
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:183)
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:136)
	at org.adempiere.pipo.srv.PipoDictionaryService.merge(PipoDictionaryService.java:104)
	at org.adempiere.plugin.utils.AdempiereActivator.packIn(AdempiereActivator.java:109)
	at org.adempiere.plugin.utils.AdempiereActivator.installPackage(AdempiereActivator.java:85)
	at org.adempiere.plugin.utils.AdempiereActivator.access$4(AdempiereActivator.java:54)
	at org.adempiere.plugin.utils.AdempiereActivator$1.run(AdempiereActivator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

09:09:50.599===========> PackIn.importXML: importXML: [41]
java.lang.RuntimeException: Unresolved elements
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:188)
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:136)
	at org.adempiere.pipo.srv.PipoDictionaryService.merge(PipoDictionaryService.java:104)
	at org.adempiere.plugin.utils.AdempiereActivator.packIn(AdempiereActivator.java:109)
	at org.adempiere.plugin.utils.AdempiereActivator.installPackage(AdempiereActivator.java:85)
	at org.adempiere.plugin.utils.AdempiereActivator.access$4(AdempiereActivator.java:54)
	at org.adempiere.plugin.utils.AdempiereActivator$1.run(AdempiereActivator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
caused by: org.adempiere.exceptions.AdempiereException: Unresolved elements
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:183)
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:136)
	at org.adempiere.pipo.srv.PipoDictionaryService.merge(PipoDictionaryService.java:104)
	at org.adempiere.plugin.utils.AdempiereActivator.packIn(AdempiereActivator.java:109)
	at org.adempiere.plugin.utils.AdempiereActivator.installPackage(AdempiereActivator.java:85)
	at org.adempiere.plugin.utils.AdempiereActivator.access$4(AdempiereActivator.java:54)
	at org.adempiere.plugin.utils.AdempiereActivator$1.run(AdempiereActivator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

09:09:50.708===========> PipoDictionaryService.merge: importXML: [41]
java.lang.RuntimeException: Unresolved elements
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:188)
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:136)
	at org.adempiere.pipo.srv.PipoDictionaryService.merge(PipoDictionaryService.java:104)
	at org.adempiere.plugin.utils.AdempiereActivator.packIn(AdempiereActivator.java:109)
	at org.adempiere.plugin.utils.AdempiereActivator.installPackage(AdempiereActivator.java:85)
	at org.adempiere.plugin.utils.AdempiereActivator.access$4(AdempiereActivator.java:54)
	at org.adempiere.plugin.utils.AdempiereActivator$1.run(AdempiereActivator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
caused by: org.adempiere.exceptions.AdempiereException: Unresolved elements
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:183)
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:136)
	at org.adempiere.pipo.srv.PipoDictionaryService.merge(PipoDictionaryService.java:104)
	at org.adempiere.plugin.utils.AdempiereActivator.packIn(AdempiereActivator.java:109)
	at org.adempiere.plugin.utils.AdempiereActivator.installPackage(AdempiereActivator.java:85)
	at org.adempiere.plugin.utils.AdempiereActivator.access$4(AdempiereActivator.java:54)
	at org.adempiere.plugin.utils.AdempiereActivator$1.run(AdempiereActivator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

09:09:50.983===========> AdempiereActivator.packIn: Pack in failed. [41]
java.lang.RuntimeException: Unresolved elements
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:188)
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:136)
	at org.adempiere.pipo.srv.PipoDictionaryService.merge(PipoDictionaryService.java:104)
	at org.adempiere.plugin.utils.AdempiereActivator.packIn(AdempiereActivator.java:109)
	at org.adempiere.plugin.utils.AdempiereActivator.installPackage(AdempiereActivator.java:85)
	at org.adempiere.plugin.utils.AdempiereActivator.access$4(AdempiereActivator.java:54)
	at org.adempiere.plugin.utils.AdempiereActivator$1.run(AdempiereActivator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
caused by: org.adempiere.exceptions.AdempiereException: Unresolved elements
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:183)
	at org.adempiere.pipo2.PackIn.importXML(PackIn.java:136)
	at org.adempiere.pipo.srv.PipoDictionaryService.merge(PipoDictionaryService.java:104)
	at org.adempiere.plugin.utils.AdempiereActivator.packIn(AdempiereActivator.java:109)
	at org.adempiere.plugin.utils.AdempiereActivator.installPackage(AdempiereActivator.java:85)
	at org.adempiere.plugin.utils.AdempiereActivator.access$4(AdempiereActivator.java:54)
	at org.adempiere.plugin.utils.AdempiereActivator$1.run(AdempiereActivator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

09:10:19.686-----------> Login.getClients: No Apps Password [38]
09:10:47.956-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.label [135]
09:10:47.956-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.tooltip [135]
09:10:55.484===========> MRole.addAccessSQL: TableName not correctly parsed - TableNameIn=C_Invoice - AccessSqlParser[C_Invoice=WHERE|0] - #1 C_Invoice=WHERE
 = SELECT C_Invoice_ID, DocumentNo, DateInvoiced, GrandTotal, PartialPayment, Balance, PaidBill FROM C_Invoice WHERE  [139]
09:15:25.542-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.label [135]
09:15:25.542-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.tooltip [135]
09:15:31.273-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.label [135]
09:15:31.273-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.tooltip [135]
09:15:35.159-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.label [135]
09:15:35.159-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.tooltip [135]
09:17:38.284-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.label [33]
09:17:38.284-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.tooltip [33]
09:17:42.640-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.label [37]
09:17:42.640-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.tooltip [37]
09:17:46.042-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.label [32]
09:17:46.042-----------> Msg.getMsg: NOT found: ni.idempiere.toolbar.button.action.report.tooltip [32]
